# Generated by Django 2.2.7 on 2020-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Un-categorized', 'Un-categorized'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Programming', 'Programming'), ('Latest Trends', 'Latest Trends')], default='Un-Categorized', max_length=20, unique=True),
        ),
    ]
